language: python
sudo: false
matrix:
    include:
    - python: "3.4"
      env: DEPS="numpy scipy nose matplotlib pytables"
    - python: "3.3"
      env: DEPS="numpy scipy nose matplotlib pytables"
    - python: "2.7"
      env: DEPS="numpy scipy nose matplotlib pytables"

install: 
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - ls /home/travis/
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then export PATH=/home/travis/miniconda/bin:$PATH; else export PATH=/home/travis/miniconda3/bin:$PATH; fi
    # See: https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
    - conda update --yes --no-deps conda
    - conda config --set always_yes yes --set changeps1 no
    # Learned the hard way: miniconda is not always up-to-date with conda.
    - conda update --yes conda
    - conda install --yes -c conda conda-env
    - conda install --yes $DEPS pip python=${TRAVIS_PYTHON_VERSION}
    - pip install coveralls 
    - python setup.py install
    - cd ~/
    - pwd

# command to run tests
script: 
    - python  -c "import opacplot2.tests as opt; opt.test(coverage=True)"

#after_success:
#    coveralls

